### ISSUE TITLE
Able to press the cassette in the Staff Menu (Minor Bug)

### ISSUE THREAD

**Issue by Stick404** [miyucomics/hexcassettes#4]
Mod Pack: HexxyCraft++ (#another_minecraft_server) 
How to reproduce: Eat cassettes, click on one in the staff casting grid, then hold down space. For some reason, this spam clicks on the cassette making a mildly funny noise of spamming "Cassette Clicks"

**Comment by miyucomics** [comment]
I don't believe this is a bug, just emergent behavior from space being used to click buttons.
