### ISSUE TITLE
Cassettes not showing in staff menu [Minor Bug] (1.20)

### ISSUE THREAD

**Issue by Stick404** [miyucomics/hexcassettes#5]
Reported by juan_gonsales2004 (xarbidarb) on Discord, cassette dont appear when in the staff menu; but they appear in the chat menu.
![image](https://github.com/user-attachments/assets/cac908a3-b1aa-43e9-bb74-e269c3fb6665)
![image](https://github.com/user-attachments/assets/23d9f0e6-1ce2-4de7-bfe1-bb2c3d7a8841)
(Link to conversation found [here](https://discord.com/channels/936370934292549712/960215808682905610/1320976215410217021))

**Comment by miyucomics** [comment]
Fixed!
